const mongoose = require('mongoose');

/**
 * Transaction Model for Payment Integration
 * 
 * This model tracks all payment transactions.
 * It stores transaction data, status, and audit trails.
 */
const transactionSchema = mongoose.Schema({
  // Core Transaction Info
  transactionId: {
    type: String,
    required: true,
    unique: true,
    index: true,
    description: 'Unique transaction identifier generated by SkillDad'
  },

  // References
  student: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
    index: true,
    description: 'Reference to the student making the payment'
  },
  course: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'Course',
    description: 'Reference to the course being purchased'
  },
  enrollment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Enrollment',
    description: 'Reference to the enrollment created after successful payment'
  },

  // Amount Details (using Decimal128 for precision)
  originalAmount: {
    type: mongoose.Types.Decimal128,
    required: true,
    description: 'Original course price before discount'
  },
  discountAmount: {
    type: mongoose.Types.Decimal128,
    default: 0,
    description: 'Discount amount applied'
  },
  finalAmount: {
    type: mongoose.Types.Decimal128,
    required: true,
    description: 'Final amount after discount'
  },
  gstAmount: {
    type: mongoose.Types.Decimal128,
    default: 0,
    description: 'GST amount if applicable'
  },
  currency: {
    type: String,
    default: 'INR',
    enum: ['INR'],
    description: 'Currency code (currently only INR supported)'
  },

  // Discount Info
  discountCode: {
    type: String,
    uppercase: true,
    description: 'Discount code applied to this transaction'
  },
  discountPercentage: {
    type: Number,
    min: 0,
    max: 100,
    description: 'Discount percentage applied'
  },

  // Payment Status
  status: {
    type: String,
    enum: ['pending', 'processing', 'success', 'failed', 'refunded', 'partial_refund'],
    default: 'pending',
    index: true,
    description: 'Current status of the transaction'
  },

  // Gateway Details
  gatewayTransactionId: {
    type: String,
    description: 'Order ID from Razorpay (razorpay_order_id)'
  },
  razorpayPaymentId: {
    type: String,
    description: 'Payment ID from Razorpay (razorpay_payment_id)'
  },
  razorpaySignature: {
    type: String,
    description: 'Payment signature from Razorpay for verification'
  },
  paymentMethod: {
    type: String,
    enum: ['card', 'netbanking', 'wallet', 'upi', 'emi', 'cardless_emi', 'paylater', 'unknown'],
    description: 'Payment method used by the student'
  },
  paymentMethodDetails: {
    cardType: {
      type: String,
      description: 'Card type (Visa, Mastercard, RuPay)'
    },
    cardLast4: {
      type: String,
      description: 'Last 4 digits of card number'
    },
    bankName: {
      type: String,
      description: 'Bank name for net banking'
    },
    upiId: {
      type: String,
      description: 'UPI ID (masked)'
    },
    walletProvider: {
      type: String,
      description: 'Wallet provider (Paytm, PhonePe, etc.)'
    }
  },

  // Session Management
  sessionId: {
    type: String,
    required: true,
    description: 'Payment session identifier'
  },
  sessionExpiresAt: {
    type: Date,
    required: true,
    description: 'Session expiration timestamp'
  },

  // Callback & Webhook Data
  callbackData: {
    type: mongoose.Schema.Types.Mixed,
    description: 'Raw callback data from payment gateway'
  },
  callbackReceivedAt: {
    type: Date,
    description: 'Timestamp when callback was received'
  },
  webhookData: [{
    data: {
      type: mongoose.Schema.Types.Mixed,
      description: 'Raw webhook data'
    },
    receivedAt: {
      type: Date,
      description: 'Timestamp when webhook was received'
    },
    processed: {
      type: Boolean,
      default: false,
      description: 'Whether webhook was successfully processed'
    }
  }],

  // Signature Verification
  callbackSignatureVerified: {
    type: Boolean,
    description: 'Whether callback signature was verified'
  },
  webhookSignatureVerified: {
    type: Boolean,
    description: 'Whether webhook signature was verified'
  },

  // Retry Management
  retryCount: {
    type: Number,
    default: 0,
    description: 'Number of retry attempts'
  },
  lastRetryAt: {
    type: Date,
    description: 'Timestamp of last retry attempt'
  },

  // Refund Details
  refundAmount: {
    type: mongoose.Types.Decimal128,
    default: 0,
    description: 'Amount refunded'
  },
  refundTransactionId: {
    type: String,
    description: 'Refund transaction ID from gateway'
  },
  refundInitiatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    description: 'Admin who initiated the refund'
  },
  refundInitiatedAt: {
    type: Date,
    description: 'Timestamp when refund was initiated'
  },
  refundCompletedAt: {
    type: Date,
    description: 'Timestamp when refund was completed'
  },
  refundReason: {
    type: String,
    description: 'Reason for refund'
  },

  // Receipt
  receiptNumber: {
    type: String,
    unique: true,
    sparse: true,
    description: 'Unique receipt number for accounting'
  },
  receiptUrl: {
    type: String,
    description: 'URL to download receipt PDF'
  },
  receiptGeneratedAt: {
    type: Date,
    description: 'Timestamp when receipt was generated'
  },

  // Reconciliation
  reconciledAt: {
    type: Date,
    description: 'Timestamp when transaction was reconciled'
  },
  reconciledBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    description: 'Finance team member who reconciled'
  },
  settlementDate: {
    type: Date,
    description: 'Settlement date from gateway'
  },
  settlementAmount: {
    type: mongoose.Types.Decimal128,
    description: 'Actual settlement amount received'
  },

  // Error Tracking
  errorCode: {
    type: String,
    description: 'Error code from gateway'
  },
  errorMessage: {
    type: String,
    description: 'Error message from gateway'
  },
  errorCategory: {
    type: String,
    enum: ['network', 'gateway', 'validation', 'insufficient_funds', 'card_declined', 'expired', 'other'],
    description: 'Category of error for analytics'
  },

  // Audit Trail
  ipAddress: {
    type: String,
    description: 'IP address of the student'
  },
  userAgent: {
    type: String,
    description: 'User agent string from browser'
  },

  // Timestamps
  initiatedAt: {
    type: Date,
    default: Date.now,
    description: 'Timestamp when payment was initiated'
  },
  completedAt: {
    type: Date,
    description: 'Timestamp when payment was completed'
  },
}, {
  timestamps: true,
});

// Indexes for performance
transactionSchema.index({ student: 1, createdAt: -1 });
transactionSchema.index({ status: 1, createdAt: -1 });
transactionSchema.index({ gatewayTransactionId: 1 });
transactionSchema.index({ razorpayPaymentId: 1 });

// TTL index for session expiration (MongoDB will automatically delete expired sessions)
transactionSchema.index({ sessionExpiresAt: 1 }, { expireAfterSeconds: 0 });

// Virtual for formatted amount
transactionSchema.virtual('finalAmountFormatted').get(function () {
  if (!this.finalAmount) return '0.00';
  return parseFloat(this.finalAmount.toString()).toFixed(2);
});

// Virtual for formatted original amount
transactionSchema.virtual('originalAmountFormatted').get(function () {
  if (!this.originalAmount) return '0.00';
  return parseFloat(this.originalAmount.toString()).toFixed(2);
});

// Virtual for formatted discount amount
transactionSchema.virtual('discountAmountFormatted').get(function () {
  if (!this.discountAmount) return '0.00';
  return parseFloat(this.discountAmount.toString()).toFixed(2);
});

// Virtual for formatted GST amount
transactionSchema.virtual('gstAmountFormatted').get(function () {
  if (!this.gstAmount) return '0.00';
  return parseFloat(this.gstAmount.toString()).toFixed(2);
});

// Ensure virtuals are included in JSON output
transactionSchema.set('toJSON', { virtuals: true });
transactionSchema.set('toObject', { virtuals: true });

module.exports = mongoose.models.Transaction || mongoose.model('Transaction', transactionSchema);
